language: java
jdk:
- oraclejdk8

dist: trusty

addons:
  sonarqube:
    organization: "Datom"

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
- sonar-scanner